# Visit https://github.com/gh-metrics/metrics/blob/master/action.yml for full reference
name: Calendar
on:
  schedule: [{cron: "0 6 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  full-year-calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: gh-metrics/metrics@master
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
