# Visit https://github.com/gh-metrics/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule: [{cron: "0 6 1 * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
#  midly-interesting-facts:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: gh-metrics/metrics@master
#        with:
#          filename: metrics.plugin.habits.facts.svg
#          token: ${{ secrets.METRICS_TOKEN }}
#          base: ""
#          plugin_habits: yes
#          plugin_habits_facts: yes
#          plugin_habits_charts: no
#          plugin_habits_from: 200
#          config_timezone: Europe/Paris
  achievement:
    runs-on: ubuntu-latest
    steps:
      - uses: gh-metrics/metrics@master
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Alexdelia
          template: classic
          base: ""
          config_timezone: Europe/Paris
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
  achievement_all:
    runs-on: ubuntu-latest
    steps:
      - uses: gh-metrics/metrics@master
        with:
          filename: metrics.plugin.achievements.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Alexdelia
          template: classic
          base: ""
          config_timezone: Europe/Paris
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
  lines-changed:
    runs-on: ubuntu-latest
    steps:
      - uses: gh-metrics/metrics@master
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_lines: yes
